### ISSUE TITLE
stuck when trying to serve a large file

### ISSUE THREAD

**Issue by abugnais** [gustavnikolaj/express-autoprefixer#14]
I'm experiencing this issue with css files larger than 20KB, 9 out of ten times the response is not being sent!

did some manual debugging, looks like this happens when the request has more than one chunk, res.on('data') is called only once for the first chunk, and res.on('end') is not being called at all

I'm calling the midddleware with these options:
{ browsers: 
     [ 'Edge 12',
       'Explorer 10',
       'Safari 7',
       'Firefox 20',
       'Chrome 20',
       'Opera 17',
       'Android 4',
       'BlackBerry 10',
       'iOS 6',
       'Firefox 28',
       'Explorer 10',
       'ExplorerMobile 10' ],
    cascade: false }

a sample file that can be used to reproduce this is attached as well.
express-autoprefixer version: 5.1.0, express version: 4.13.1, node version 6.2.2

[sample.css.zip](https://github.com/gustavnikolaj/express-autoprefixer/files/393374/sample.css.zip)

**Comment by gustavnikolaj** [comment]
Fixed by v5.1.1 by upgrading hijackresponse. https://github.com/gustavnikolaj/hijackresponse/issues/10
