### ISSUE TITLE
Get up to speed with autoprefixer module

### ISSUE THREAD

**Issue by mwoc** [gustavnikolaj/express-autoprefixer#5]
They're now at 5.0

We should also make sure this will be handled at an appropriate level:

Error: autoprefixer: autoprefixer(browsers) is deprecated and will be removed in 3.1. Use autoprefixer({ browsers: browsers }).

**Comment by Munter** [comment]
If there hasn't been any breaking changes, then we should just change `~` to a `>` in peerDependencies and update the devDependencies. Since we leave the specific version up to the individual developer this shouldn't be a big deal

**Comment by mwoc** [comment]
From 3.0 to 3.1 they did do a breaking change according to the deprecation message. Though if express-autoprefixer is the correct level of checking for such breaking changes I'm not so sure, as it's a quite thin wrapper.

**Comment by gustavnikolaj** [comment]
I tagged a new version 3.0.0 which is listing autoprefixer 5 as a peer dependency.
