### ISSUE TITLE
Autoprefixer's process() method is deprecated

### ISSUE THREAD

**Issue by Xiphe** [gustavnikolaj/express-autoprefixer#8]
When i use this plugin i'm getting a note:

`Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead`

apparently, autoprefixer will not be usable as standalone package in the future, but instead be a plugin for [postcss](https://github.com/postcss/postcss)

**Comment by gustavnikolaj** [comment]
Thank you for the heads up. I'll make sure to look into it. :-) If you do have additional information, like when it is likely to stop working, it'd be much appreciated.

**Comment by Xiphe** [comment]
no idea when it actually will be removed. I'm just annoyed by the deprecation warnings ;)
